name: Tests
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16

    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate mock implementations
      run: go generate

    - name: Test
      run: go test ./...
